### ISSUE TITLE
Features wanted and todo-list for 1.0.0 release

### ISSUE THREAD

**Issue by 05K4R** [05K4R/soundcloud-rate-profiles#1]
# Required features
- [ ] Ability to create, manage and remove custom categories and labels
- [ ] Automatically update reposts and add date when a previously categorized track is played again
- [ ] Ability to reset all data
# Other wanted features
- [ ] See and modify old categorized tracks information
- [ ] Set threshold for notification if a profile isn't worth to keep following
- [ ] Set cutoff amount for when to ignore track rating
# Things to do before release
- [ ] Add Chrome Web Store information (icon, screenshots, rename extension, etc...)
- [ ] Decide a proper licence for the code that's compatible with libraries in the project

**Comment by 05K4R** [comment]
No longer developing this extension
